services:
  malwee-database: 
    image: mysql
    networks:
      - malwee-network  
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
      
  malwee-backend:
    image: malwee
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - malwee-database
    environment:
      - DB_HOST=malwee-database
    ports:
      - 60:60  
    networks:
      - malwee-network

networks:
  malwee-network:
    driver: bridge

volumes:
    db_data: